# This is a basic workflow to help you get started with Actions

name: Qodana

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, v2.0 ]
  pull_request:
    branches: [ master, v2.0 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/work/_temp/_github_home/cache
          key: ${{ runner.os }}-qodana-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-qodana-${{ github.ref }}
            ${{ runner.os }}-qodana-
      - uses: docker://jetbrains/qodana-<linter>
        with:
          args: --cache-dir=/github/home/cache --results-dir=/github/workspace/qodana --save-report --report-dir=/github/workspace/qodana/report
      - uses: actions/upload-artifact@v2
        with:
          path: qodana
